<template><section class="answer-chart"><h3>{{ chart.title }}</h3><div ref="container" class="answer-chart__canvas"></div><p v-if="chart.conclusion">{{ chart.conclusion }}</p><small v-if="chart.source">数据来源：{{ chart.source }}</small></section></template>
<script setup lang="ts">
import { nextTick, onBeforeUnmount, onMounted, ref, watch } from "vue";
import * as echarts from "echarts";
const props = defineProps<{ chart: { type: "line" | "bar" | "pie"; title: string; x_axis: string[]; series: Array<{ name: string; data: number[] }>; unit: string; conclusion: string; source: string } }>();
const container = ref<HTMLElement>(); let instance: echarts.ECharts | undefined;
function render() { if (!container.value) return; instance ||= echarts.init(container.value, undefined, { renderer: "svg" }); const c = props.chart; const isPie = c.type === "pie"; instance.setOption({ color:["#36d6f4","#4f89ff","#43d6a0","#ffbf69"], tooltip:{trigger:isPie?"item":"axis",backgroundColor:"#081f37",borderColor:"#2a6284",textStyle:{color:"#eaf8ff"}}, legend:{show:c.series.length>1, bottom:0,textStyle:{color:"#a8c6dc"}}, grid:isPie?undefined:{left:42,right:18,top:22,bottom:36}, xAxis:isPie?undefined:{type:"category",data:c.x_axis,axisLine:{lineStyle:{color:"#2a5472"},},axisLabel:{color:"#8eafc8"}}, yAxis:isPie?undefined:{type:"value",name:c.unit,nameTextStyle:{color:"#8eafc8"},axisLabel:{color:"#8eafc8"},splitLine:{lineStyle:{color:"#183d5a"}}}, series:isPie?[{type:"pie",radius:["42%","70%"],label:{color:"#b8d3e4"},data:c.x_axis.map((name,index)=>({name,value:c.series[0]?.data[index]||0}))}]:c.series.map(s=>({name:s.name,type:c.type,smooth:c.type==="line",barMaxWidth:34,data:s.data})) }, true); }
onMounted(async()=>{await nextTick(); render(); window.addEventListener("resize", resize);}); watch(()=>props.chart, render,{deep:true}); function resize(){instance?.resize();} onBeforeUnmount(()=>{window.removeEventListener("resize",resize);instance?.dispose();});
</script>
<style scoped>.answer-chart{margin:16px 0;padding:16px;border:1px solid #245676;background:#081f37}.answer-chart h3{margin:0 0 8px;color:#dff8ff;font-size:15px}.answer-chart__canvas{height:260px}.answer-chart p{margin:8px 0 2px;color:#b4cde0;font-size:13px}.answer-chart small{color:#7fa6c1;font-size:12px}</style>
